# Используем Node.js для сборки
FROM node:20 AS builder
WORKDIR /app

# Устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем весь код и собираем
COPY . .
RUN npm run build

# Финальный образ с Nginx для раздачи статики
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
