FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --cache-min 9999999

COPY . .

RUN npm run build --production

CMD ["node", "--max-old-space-size=4096", "node_modules/react-scripts/bin/react-scripts.js", "start"]
